### ISSUE TITLE
Support for allOf

### ISSUE THREAD

**Issue by slecholineas** [bjansen/swagger-schema-validator#10]
In the swagger I'm using, "allOf" is being used:
            allOf:
              - $ref: '#/definitions/assignment'
              - $ref: '#/definitions/wagonSummary'
              - $ref: '#/definitions/wagons'

How do I specify those definitions in the validate method ?

**Comment by bjansen** [comment]
I adapted the OpenAPI 3 sample [located here](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof) to make it work with `swagger-schema-validator`. Here is how it looks like:

```yaml
definitions:
  Pet:
    type: object
    required:
      - pet_type
    properties:
      pet_type:
        type: string
    discriminator:
      propertyName: pet_type
  Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
    x-allOf: # Combines the main `Pet` schema with `Dog`-specific properties
      - $ref: '#/definitions/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: boolean
          breed:
            type: string
            enum: [Dingo, Husky, Retriever, Shepherd]
```

So I think your example should simply be:

```yaml
x-allOf:
- $ref: '#/definitions/assignment'
- $ref: '#/definitions/wagonSummary'
- $ref: '#/definitions/wagons'
```

Then use

```
        ProcessingReport report = validator.validate(myJsonString, "/definitions/Dog");
```

**Comment by bjansen** [comment]
See https://github.com/bjansen/swagger-schema-validator/commit/768c3fa446b504c51a4b98cf3c8a6d89d04e93be for a complete example.
