### ISSUE TITLE
fatal: danglingRef

### ISSUE THREAD

**Issue by abergmeier** [bjansen/swagger-schema-validator#11]
Currently we get `com.github.fge.jsonschema.core.exceptions.JsonReferenceException: fatal: danglingRef`.
at
```
at com.github.fge.jsonschema.main.JsonValidator.buildJsonSchema(JsonValidator.java:190) ~[json-schema-validator-2.2.13.jar:na]
```

**Comment by abergmeier** [comment]
Which might be correct - but it would be good to have some context where the danglingRef occurs.

**Comment by bjansen** [comment]
Hi,

Could you provide an example of a swagger file that triggers this error please?

**Comment by bjansen** [comment]
This might happen if you reference a definition that doesn't exist when calling `validate()`. It used to throw a NPE in the previous version.

**Comment by bjansen** [comment]
Version 0.4.1 was just published with a fix for this.
