### ISSUE TITLE
Expected contract violation does not occur

### ISSUE THREAD

**Issue by P3trur0** [bjansen/swagger-schema-validator#13]
Hi @bjansen,

thanks for this helpful library.

I am using it for my swagger validations, but I noticed a strange behavior while validating an Open API contract.

Basically, doing a response validation given a specific response type, e.g.:

```
"ResponseBean":{
            "type":"object",
            "properties":{
               "hello":{
                  "type":"string"
               },
               "there":{
                  "type":"string"
               }
            }
         }
```

it goes ok without problems. Alas, if I change the contract by adding few more attributes, e.g.:

```
"ResponseBean":{
            "type":"object",
            "properties":{
               "hello":{
                  "type":"string"
               },
               "there":{
                  "type":"string"
               },
               "howAre":{
                  "type":"string"
               },
               "you":{
                  "type":"string"
               }
            }
         }
```

it keeps on assert true, although I'd expect an error because of missing fields in the actual Java response object. Do you have any idea about solving this behavior?

Thank you!

**Comment by bjansen** [comment]
Hi,

Do you mean that if the actual JSON string that you are trying to validate is:

```json
{
    "hello": "world",
    "there": "okay"
}
```

then the validation does not fail, and you expect it to fail?

**Comment by P3trur0** [comment]
Hi, thanks for the quick reply. Basically with Open API 3.0, the validation are failing if the contract changed from string to integer or vice versa, but contract doesn't fail incase if a new attribute is added or old attribute is deleted.

However, it seems that same works well with Swagger 2.0.

Later I'll try to provide a more detailed example.

**Comment by bjansen** [comment]
Well attributes are optional by default, so unless you mark new attributes as `required`, the validator will not complain if they are not present in the payload:

```json
"ResponseBean":{
            "type":"object",
            "required": ["hello", "there"],
            "properties":{
               "hello":{
                  "type":"string"
               },
               "there":{
                  "type":"string"
               },
               "howAre":{
                  "type":"string"
               },
               "you":{
                  "type":"string"
               }
            }
         }
```

To be honest, this library was created for Swagger (V2) definitions, I'm not even sure it works correctly with OpenAPI (V3) definitions.

**Comment by P3trur0** [comment]
Hi @bjansen ok, thanks for your clarifications.

Just to explain the problem better...

Consider I have this contract:

```json
"ResponseBean":{
            "type":"object",
            "properties":{
               "hello":{
                  "type":"string"
               },
               "there":{
                  "type":"string"
               }
            }
         }

```
And this payload:

`{"hello":"World","there":"Hi"}`

So, I run the validation and it goes ok.

Later, I change my contract like this (i.e.: I remove the final '`o`' from the '`hello`' field):

```json
"ResponseBean":{
            "type":"object",
            "properties":{
               "hell":{
                  "type":"string"
               },
               "there":{
                  "type":"string"
               }
            }
         }
```
And, given the same payload as before, the validation still goes ok.  

Instead, If I do the following change (i.e.: I change the data type of the "`hello`" property):

```json
"ResponseBean":{
            "type":"object",
            "properties":{
               "hello":{
                  "type":"integer"
               },
               "there":{
                  "type":"string"
               }
            }
         }
```

And given the same payload as before, the validation fails as expected.

---

Hope the scenario is clearer now. As you suggest above, it might be due to the missing `required` attribute.

Meanwhile, as alternative, I'd consider to make my OpenAPI 3.x contact more strict by using the `required` attribute.

**Comment by bjansen** [comment]
Ok thanks for the clarification, I'll take a look when I have time.

**Comment by bjansen** [comment]
`swagger-schema-validator` is basically a bridge between `swagger-core` (the schema parser) and `json-schema-validator` (the actual validator). Unfortunately, is looks like it's a bug in `json-schema-validator`: https://github.com/java-json-tools/json-schema-validator/issues/211

I'll try to dig into this library to see if there is a possible fix or workaround. Thanks for reporting the problem.

**Comment by P3trur0** [comment]
Thanks for the investigation!

**Comment by P3trur0** [comment]
Thanks for the investigation!

**Comment by bjansen** [comment]
Hi, and sorry for the late reply!
I found out recently that JSON Schema has an `additionalProperties` object property that you can set to `false` to disallow extra properties.

So, given this schema:

```json
    "definitions": {
        "ResponseBean": {
            "type": "object",
            "required": ["hello"],
            "additionalProperties": false,
            "properties": {
                "hello": {
                    "type": "string"
                },
                "there": {
                    "type": "string"
                }
            }
        }
    }
```

And this payload:

```json
{
  "hell": "World",
  "there": "Hi"
}
```

The validation will fail as expected with these two errors:

```
[error: object instance has properties which are not allowed by the schema: ["hell"]
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/ResponseBean"}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "additionalProperties"
    unwanted: ["hell"]
, error: object has missing required properties (["hello"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/ResponseBean"}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["hello"]
    missing: ["hello"]
]
```

Hope that helps.
