### ISSUE TITLE
Generic definitionPointer

### ISSUE THREAD

**Issue by s16508pjwstk** [bjansen/swagger-schema-validator#14]
Hi, I've just implemented your validator and I have one problem.

Lets say I've got huge JSON swagger definition with multiple properties. Simplified example below.

````definitions: \
  User:
    x-oneOf: [{required: ["id"]}, {required: ["name"]}]
    properties:
      id:
        type: integer
      name:
        type: string
  Data:
    properties:
      id:
        type: integer
      description:
        type: string
  History:
    properties:
      id:
        type: integer
      description:
        type: string
`````

I want to perform a validation for whole JsonSchema printed above without specification which object of definitions should be validated.
Now, I have to run them explicitly

````
ProcessingReport report = validator.validate(jsonNode, "/definitions/User");
ProcessingReport report = validator.validate(jsonNode, "/definitions/Data");
ProcessingReport report = validator.validate(jsonNode, "/definitions/History");
````

Is there any possibility to pass definitionPointer argument which validates whole schema?.

Thank you in advance,
Kacper

**Comment by bjansen** [comment]
Hi, what you are trying to do is currently not possible. I'm not sure I understand your example though. Is a User also a Data *and* a History? The definitions are all the same in your example, so validating against any of them should be enough.

**Comment by s16508pjwstk** [comment]
Yeah, that was a shortcut from my side.
Of course each of them is a different entity to be validated and each of them is a standalone object.

**Comment by bjansen** [comment]
It should work with `ProcessingReport report = validator.validate(jsonNode, "/definitions/Response");`.

It works fine with the following spec:
```json
{
    "swagger": "2.0",
    "info": {
        "title": "Sample API",
        "version": "1"
    },
    "definitions": {
        "Response": {
            "type": "object",
            "required": [
                "asyncRequestId",
                "result"
            ],
            "properties": {
                "asyncRequestId": {
                    "type": "string"
                },
                "beginTime": {
                    "type": "string",
                    "format": "date-time"
                },
                "endTime": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/AsyncResult"
                },
                "sceuid": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "AsyncResult": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}
```

and the following sample:

```json
{
    "asyncRequestId": "qsdf",
    "result": {

    }
}
```

If the reference points to a definition located in an external file, the validation will fail (see #3).

**Comment by bjansen** [comment]
If I set `status` as `required` in `AsyncResult` and try to validate the same input, the processing report will contain an error:

> error: object has missing required properties (["type"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/AsyncResult"}
    instance: {"pointer":"/result"}
    domain: "validation"
    keyword: "required"
    required: ["type"]
    missing: ["type"]

-> it works as expected

**Comment by s16508pjwstk** [comment]
Everything works perfectly, thank you.
