### ISSUE TITLE
It looks like Open API type int64 is not supported.

### ISSUE THREAD

**Issue by dbazim** [bjansen/swagger-schema-validator#4]
I have got a warning 
warning: format attribute "int64" not supported
when validating request. The type is defined here 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#dataTypes

the schema definition looks like
...
                "quantity": {
                    "description": "Quantity ordered",
                    "type": "integer",
                    "format": "int64"
                },
...
Can you please improve the implementation to support that type.

Thank you.

**Comment by bjansen** [comment]
Fixed, I'll release the new version soon.

**Comment by bjansen** [comment]
Just released 0.1.3, it should appear in Maven Central very soon.

**Comment by dbazim** [comment]
Thank you!
