### ISSUE TITLE
Deepcheck option for SwaggerValidator validate() method

### ISSUE THREAD

**Issue by timatanu** [bjansen/swagger-schema-validator#6]
Several "pure" JSON Schema implementations provide a deepcheck parameter such that processing does not stop at the current level once an error is detected. It would be a nice feature to have in SwaggerValidator.

**Comment by timatanu** [comment]
Hello Bastien,

Will let you know how things go when I update my code to use the new feature.


Tim Armstrong


________________________________

**Comment by bjansen** [comment]
Hi,

I'll make a release today in case you want to avoid building the project
yourself.

Bastien

**Comment by timatanu** [comment]
Many thanks.
I use Java but wouldn't not claim any degree of expertise these days.


Tim Armstrong


________________________________

**Comment by bjansen** [comment]
Version 0.4.0 should land in Maven Central in a couple hours.

**Comment by timatanu** [comment]
Works a treat.
Many thanks.


Tim Armstrong


________________________________
